[theme]
primaryColor="#a3cef1"           # Soft Sky Blue
backgroundColor="#f6f9fa"        # Very Light Gray
secondaryBackgroundColor="#f7e8d0" # Light Cream
textColor="#3a3a3a"              # Charcoal Gray